/**
*  Description     :  Parent/base Class with keyword virtual
*
*  Created By      :  Nidhi Kumari
*
*  Created Date    :  06/28/2022
*
*  Revision Logs   :    V1.0 - Created - Nidhi Kumari
*				    . 
*
**/
public virtual class InheritanceParentClass {
    public void parentClassMethod(){
        System.debug('Print First Line of Parent Class');
    }
    public void parentClassMethod2(){
        System.debug('print second line of parent class');
    }
    public void parentClassMethod3(){
        System.debug('print Third line of parent class');
    }
}