/**
*  Description     :  Sellers Purchase Order Class
*
*  Created By      :  Nidhi Kumari
*
*  Created Date    :  06/29/2022
*
*  Revision Logs   :    V1.0 - Created - Nidhi Kumari
*				   
*
**/
public with sharing class ThisKeyword {
    
    String str;
    {
        this.str = 'TestString';
    }

    //first constructor for the class
    public thisKeyword(String str2){

    }

    //second constructor for the class
    public ThisKeyword(){
        this('none');

    }

}